export enum GETSingleUserType {
    GET_SINGLE_USER_SUCCESS = 'GET_SINGLE_USER_SUCCESS',
    GET_SINGLE_USER_REQUEST = 'GET_SINGLE_USER_REQUEST',
    GET_SINGLE_USER_FAIL = 'GET_SINGLE_USER_FAIL',
}

export enum GETAllUserType {
    GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS',
    GET_ALL_USER_REQUEST = 'GET_ALL_USER_REQUEST',
    GET_ALL_USER_FAIL = 'GET_ALL_USER_FAIL',
}

export enum CREATEVaccinatedUserType {
    CREATE_VACCINATED_USER_SUCCESS = 'CREATE_VACCINATED_USER_SUCCESS',
    CREATE_VACCINATED_USER_REQUEST = 'CREATE_VACCINATED_USER_REQUEST',
    CREATE_VACCINATED_USER_FAIL = 'CREATE_VACCINATED_USER_FAIL',
}
